name: senior_project_env
channels:
  - defaults
dependencies:
  - asgiref=3.3.0=py_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - django=3.1.2=py_0
  - krb5=1.17.1=hc04afaa_0
  - libpq=12.2=h3235a2c_0
  - openssl=1.1.1h=he774522_0
  - pip=20.2.3=py38_0
  - psycopg2=2.8.5=py38h7a1dbc1_0
  - python=3.8.5=h5fd99cc_1
  - pytz=2020.1=py_0
  - setuptools=50.3.0=py38h9490d1a_1
  - sqlite=3.33.0=h2a8f88b_0
  - sqlparse=0.4.1=py_0
  - tk=8.6.10=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py38_0
  - zlib=1.2.11=h62dcd97_4
prefix: G:\Anaconda\envs\senior_project_env

